application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  last_run: ootb_encode_decode_hash_str
  log_level: INFO #  FATAL | CRITICAL | ERROR | WARNING | INFO | DEBUG
  version: 1.0.2
