application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  execute_on_startup: true
  http_port: 8866
  last_run: OOTB_MATPLOTLIB_VIEW
  log_level: INFO
  version: 1.0.4
