application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  execute_on_startup: false
  last_run: ootb_keep_screen_unlocked
  log_level: INFO
  version: 1.0.3
