application:
  app_name: petp
  author: lorisunjunbin@DalianChina
  cell: +86-13478653323
  email: 6099012@qq.com
  execute_on_startup: false
  last_run: test_read_excel_loop_each_row_show
  log_level: INFO
  version: 1.0.3
